# Generated by Django 4.1.6 on 2023-03-14 06:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MpesaPayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phone_number", models.CharField(max_length=20)),
                ("referrence", models.CharField(max_length=255)),
                ("merchant_request_id", models.CharField(max_length=255)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("checkout_request_id", models.CharField(max_length=120)),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("INITIATING", "INITIATING"),
                            ("CREATED", "CREATED"),
                            ("SETTLED", "SETTLED"),
                            ("SUSPENSE", "SUSPENSE"),
                            ("FAILED", "FAILED"),
                        ],
                        default=[
                            ("INITIATING", "INITIATING"),
                            ("CREATED", "CREATED"),
                            ("SETTLED", "SETTLED"),
                            ("SUSPENSE", "SUSPENSE"),
                            ("FAILED", "FAILED"),
                        ],
                        max_length=60,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name="Payment",
        ),
    ]
