# Generated by Django 4.1.6 on 2023-03-14 07:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0004_payment_response_code_payment_response_desc_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="customer_message",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
