# Generated by Django 4.1.6 on 2023-03-14 07:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0005_payment_customer_message"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Payment",
            new_name="MpesaPayment",
        ),
    ]
