# Generated by Django 4.1.6 on 2023-03-15 08:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0006_rename_payment_mpesapayment"),
    ]

    operations = [
        migrations.AddField(
            model_name="mpesapayment",
            name="mpesa_receipt_number",
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="mpesapayment",
            name="transaction_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
