# Generated by Django 4.1.6 on 2023-03-15 08:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0007_mpesapayment_mpesa_receipt_number_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="mpesapayment",
            old_name="mpesa_receipt_number",
            new_name="trans_id",
        ),
    ]
