# Generated by Django 4.1.6 on 2023-03-15 08:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0008_rename_mpesa_receipt_number_mpesapayment_trans_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mpesapayment",
            name="referrence",
        ),
        migrations.AddField(
            model_name="mpesapayment",
            name="referrence_id",
            field=models.CharField(
                default=django.utils.timezone.now,
                max_length=255,
                verbose_name="Refrence ID",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="mpesapayment",
            name="checkout_request_id",
            field=models.CharField(max_length=120, verbose_name="Checkout Request ID"),
        ),
        migrations.AlterField(
            model_name="mpesapayment",
            name="merchant_request_id",
            field=models.CharField(max_length=255, verbose_name="Merchant Request ID"),
        ),
        migrations.AlterField(
            model_name="mpesapayment",
            name="phone_number",
            field=models.CharField(max_length=20, verbose_name="Phone Number"),
        ),
        migrations.AlterField(
            model_name="mpesapayment",
            name="trans_id",
            field=models.CharField(max_length=255, verbose_name="Mpesa Transaction ID"),
        ),
    ]
