# Generated by Django 4.1.6 on 2023-03-15 08:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0009_remove_mpesapayment_referrence_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mpesapayment",
            name="transaction_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
