# Generated by Django 4.1.6 on 2023-03-15 13:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0010_alter_mpesapayment_transaction_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mpesapayment",
            name="customer_message",
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="mpesapayment",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("INITIATING", "INITIATING"),
                    ("PENDING", "PENDING"),
                    ("CANCELED", "CANCELED"),
                    ("SUCCESS", "SUCCESS"),
                ],
                default="INITIATING",
                max_length=60,
            ),
        ),
        migrations.AlterField(
            model_name="mpesapayment",
            name="response_desc",
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="mpesapayment",
            name="result_desc",
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
