# Generated by Django 4.1.6 on 2023-03-17 11:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0011_alter_mpesapayment_customer_message_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mpesapayment",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("INITIATING", "INITIATING"),
                    ("PENDING", "PENDING"),
                    ("CANCELED", "CANCELED"),
                    ("SUCCESS", "SUCCESS"),
                    ("FAILED", "FAILED"),
                ],
                default="INITIATING",
                max_length=60,
            ),
        ),
        migrations.AlterField(
            model_name="mpesapayment",
            name="trans_id",
            field=models.CharField(
                default=None, max_length=255, verbose_name="Mpesa Transaction ID"
            ),
        ),
    ]
