# Generated by Django 4.1.6 on 2023-03-17 11:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0012_alter_mpesapayment_payment_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mpesapayment",
            name="trans_id",
            field=models.CharField(
                default=None,
                max_length=255,
                null=True,
                verbose_name="Mpesa Transaction ID",
            ),
        ),
    ]
