# Generated by Django 4.1.6 on 2023-03-18 12:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0017_alter_userprofile_user_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userprofile",
            old_name="user_id",
            new_name="user",
        ),
    ]
