# Generated by Django 4.1.6 on 2023-03-18 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0018_rename_user_id_userprofile_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mpesapayment',
            options={'ordering': ('-created_at',), 'verbose_name_plural': 'Mpesa Payments'},
        ),
    ]
